// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk3gtMXqVwtle21oz5xoWIr6qQWo-daIU',
    appId: '1:548974999259:web:bbd43d7200c4230a0a7efe',
    messagingSenderId: '548974999259',
    projectId: 'evently-6f059',
    authDomain: 'evently-6f059.firebaseapp.com',
    storageBucket: 'evently-6f059.firebasestorage.app',
    measurementId: 'G-LDZ62K18EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa-BagV3blSq6myTvQgWoLbJNnW17NDyg',
    appId: '1:548974999259:android:e828538560182b4c0a7efe',
    messagingSenderId: '548974999259',
    projectId: 'evently-6f059',
    storageBucket: 'evently-6f059.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIkaHcWcoJIfcQBhiNbzmkj4VUSJ0RBCw',
    appId: '1:548974999259:ios:43838f7cfeec083f0a7efe',
    messagingSenderId: '548974999259',
    projectId: 'evently-6f059',
    storageBucket: 'evently-6f059.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );
}
